from consts import *

class Options:

    def __init__(self) -> None:
        self.POINTS_DISTANCE = DEFAULT_POINTS_DISTANCE 
        self.POINTS_DISTANCE_RANDOMNESS = DEFAULT_POINTS_DISTANCE_RANDOMNESS
        self.POINTS_POSITIONING_ITERATIONS = DEFAULT_POINTS_POSITIONING_ITERATIONS
        self.POINTS_RADIUS = DEFAULT_POINTS_RADIUS

        self.N_VERTICES_RANDGRAPH = DEFAULT_N_VERTICES_RANDGRAPH

        self.NEIGHBORS_INTERVAL = DEFAULT_NEIGHBORS_INTERVAL

        self.DELETE_PROBABILITY = DEFAULT_DELETE_PROBABILITY